[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Client-side routing uchun redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
